<?php

namespace App\Contracts;


interface Constant
{
    /**
     * Constant variables
     */
    const STATUS_INTEGER_ACTIVE = 1;
    const STATUS_INTEGER_INACTIVE = 0;
    const STATUS_INTEGER_DELETED = 2;
    const STATUS_TEXT_ACTIVE = 'ACTIVE';
    const STATUS_TEXT_INACTIVE = 'INACTIVE';

    const ALLOWED_INTEGER_POSITIVE = 1;
    const ALLOWED_INTEGER_NEGATIVE = 0;
    const ALLOWED_DEPOSIT_TEXT_ALLOWED = "ALLOWED";
    const ALLOWED_DEPOSIT_TEXT_NOT_ALLOWED = "NOT ALLOWED";
    const ALLOWED_DEPOSIT_INTEGER_ALLOWED = 1;
    const ALLOWED_DEPOSIT_INTEGER_NOT_ALLOWED = 0;

    const MERCHANT_TYPE_TEXT_MAIN_MERCHANT = "MAIN MERCHANT";
    const MERCHANT_TYPE_TEXT_BRANCH_MERCHANT = "BRANCH MERCHANT";
    const MERCHANT_TYPE_TEXT_FRANCHISED = "FRANCHISED";

    const MERCHANT_TYPE_INTEGER_MAIN_MERCHANT = 1;
    const MERCHANT_TYPE_INTEGER_BRANCH_MERCHANT = 2;
    const MERCHANT_TYPE_INTEGER_FRANCHISED = 3;

    const DEFAULT_COUNTRY = "USA";
    const DEFAULT_STATE = "NY";
    const DEFAULT_ESTIMATED_DURATION = 30;

    const BANNER_TYPE_IMAGE = "IMAGE";
    const BANNER_TYPE_VIDEO = "VIDEO";

    const PRODUCT_TYPE_IN_STOCK = "IN STOCK";
    const PRODUCT_TYPE_OUT_OF_STOCK = "OUT OF STOCK";

    const CUSTOMER_TYPE_GUEST = "GUEST";
    const CUSTOMER_TYPE_MEMBER = "MEMBER";

    const SMS_REQUEST_STATUS_NEW = "NEW";
    const SMS_REQUEST_STATUS_APPROVED = "APPROVED";
    const SMS_REQUEST_STATUS_REJECTED = "REJECTED";

    const GRID_VIEW_EDIT_BUTTON = "mode_edit";
    const GRID_VIEW_DELETE_BUTTON = "delete_forever";
    const GRID_VIEW_ADD_BUTTON = "add";
    const GRID_VIEW_CHANGE_PASSWORD = "vpn_key";
    const GRID_VIEW_CONNECTION_ACTIVE = "visibility";
    const GRID_VIEW_CONNECTION_INACTIVE = "visibility_off";

    const MODULE_TYPE_MAIN = "MAIN";
    const MODULE_TYPE_SETTINGS = "SETTINGS";
    const MODULE_TYPE_INTEGER_MAIN = 2;
    const MODULE_TYPE_INTEGER_SETTINGS = 1;
    const MODULE_DEFAULT_SETTINGS_MATERIALIZED_ICON = "launch";

    const PERMISSION_TYPE_CREATE = "create";
    const PERMISSION_TYPE_READ = "read";
    const PERMISSION_TYPE_UPDATE = "update";
    const PERMISSION_COLOR_GREEN = "bg-green";
    const PERMISSION_COLOR_GREY = "bg-grey";

    const USERTYPE_INTEGER_ADMIN = 1;
    const USERTYPE_INTEGER_CUSTOMER = 2;

    const RESERVATION_STATUS_INTEGER_PENDING_PAYMENT = 1;
    const RESERVATION_STATUS_INTEGER_PAID = 2;
    const RESERVATION_STATUS_INTEGER_OCCUPIED = 3;
    const RESERVATION_STATUS_INTEGER_DONE = 4;
    const RESERVATION_STATUS_INTEGER_CANCELLED = 5;

    const RESERVATION_STATUS_PENDING_PAYMENT = "PENDING PAYMENT";
    const RESERVATION_STATUS_PAID = "PAID";
    const RESERVATION_STATUS_OCCUPIED = "CHECK IN";
    const RESERVATION_STATUS_DONE = "DONE";
    const RESERVATION_STATUS_CANCELLED = "CANCELLED";

    const RESERVATION_TYPE_AM = "Morning Rate";
    const RESERVATION_TYPE_PM = "Night Rate";
}
